name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile tests
      run: |
        gcc multiplicar.c dividir.c operacoesmatematicas_test.c -o testes

    - name: Run tests
      run: ./testes
